import { Type } from './types'

export enum Mastery {
    Beginner,
    Intermediate,
    Advanced,
}

export const technologies: Content.Technology[] = [
    {
        id: 'tailwindcss',
        name: 'Tailwind CSS',
        type: Type.Framework,
        icon: 'tailwindcss',
        url: 'https://tailwindcss.com/',
        mastery: Mastery.Advanced,
    },
    
    {
        id: 'react',
        name: 'React',
        type: Type.Library,
        icon: 'react',
        url: 'https://react.dev/',
        mastery: Mastery.Advanced,
    },
    {
        id: 'typescript',
        name: 'TypeScript',
        type: Type.Language,
        icon: 'typescript',
        url: 'https://typescriptlang.org/',
        mastery: Mastery.Advanced,
    },
    {
        id: 'javascript',
        name: 'JavaScript',
        type: Type.Language,
        icon: 'javascript',
        url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
        mastery: Mastery.Advanced,
    },
    {
        id: 'c++',
        name: 'C++',
        type: Type.Language,
        icon: 'cplusplus',
        url: 'https://isocpp.org/',
        mastery: Mastery.Advanced,
    },
    {
        id: 'nodejs',
        name: 'Node.js',
        type: Type.Framework,
        icon: 'nodejs',
        url: 'https://nodejs.org/',
        mastery: Mastery.Advanced,
    },
    {
        id: 'mysql',
        name: 'MySQL',
        type: Type.Database,
        icon: 'mysql',
        url: 'https://mysql.com/',
        mastery: Mastery.Advanced,
    },
    {
        id: 'postgresql',
        name: 'PostgreSQL',
        type: Type.Database,
        icon: 'postgresql',
        url: 'https://postgresql.org/',
        mastery: Mastery.Advanced,
    },
    {
        id: 'mongodb',
        name: 'MongoDB',
        type: Type.Database,
        icon: 'mongodb',
        url: 'https://mongodb.com/',
        mastery: Mastery.Intermediate,
    },
    {
        id: 'docker',
        name: 'Docker',
        type: Type.Devops,
        icon: 'docker',
        url: 'https://docker.com/',
        mastery: Mastery.Advanced,
    },
    {
        id: 'markdown',
        name: 'Markdown',
        type: Type.Language,
        icon: 'markdown',
        url: 'https://daringfireball.net/projects/markdown/',
        mastery: Mastery.Advanced,
    },
    {
        id: 'html',
        name: 'HTML',
        type: Type.Language,
        icon: 'html5',
        url: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
        mastery: Mastery.Advanced,
    },
    {
        id: 'css',
        name: 'CSS',
        type: Type.Language,
        icon: 'css3',
        url: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
        mastery: Mastery.Advanced,
    },
   
    // {
    //     id: 'csharp',
    //     name: 'C#', 
    //     type: Type.Language,
    //     icon: 'csharp',
    //     url: 'https://docs.microsoft.com/en-us/dotnet/csharp/',
    //     mastery: Mastery.Beginner,
    // },
    {
        id: 'c',
        name: 'C',
        type: Type.Language,
        icon: 'c',
        url: 'https://en.wikipedia.org/wiki/C_(programming_language)',
        mastery: Mastery.Beginner,
    },
    // {
    //     id: 'rust',
    //     name: 'Rust',
    //     type: Type.Language,
    //     icon: 'rust',
    //     url: 'https://rust-lang.org/',
    //     mastery: Mastery.Intermediate,
    // },
    {
        id: 'bash',
        name: 'Bash',
        type: Type.Language,
        icon: 'bash',
        url: 'https://gnu.org/software/bash/',
        mastery: Mastery.Intermediate,
    },
    {
        id: 'powershell',
        name: 'PowerShell',
        type: Type.Language,
        icon: 'https://cdn.icon-icons.com/icons2/2107/PNG/512/file_type_powershell_icon_130243.png',
        url: 'https://learn.microsoft.com/fr-fr/powershell/scripting/overview?view=powershell-7.3',
        mastery: Mastery.Beginner,
    },
    // {
    //     id: 'go',
    //     name: 'Go',
    //     type: Type.Language,
    //     icon: 'go',
    //     url: 'https://golang.org/',
    //     mastery: Mastery.Beginner,
    // },
    {
        id: 'git',
        name: 'Git',
        type: Type.Tool,
        icon: 'git',
        url: 'https://git-scm.com/',
        mastery: Mastery.Advanced,
    },
    {
        id: 'github',
        name: 'GitHub',
        type: Type.Tool,
        icon: 'github not-colored',
        url: 'https://github.com/',
        mastery: Mastery.Advanced,
    },
    {
        id: 'vsc',
        name: 'Visual Studio Code',
        type: Type.Tool,
        icon: 'vscode',
        url: 'https://code.visualstudio.com/',
        mastery: Mastery.Advanced,
    },
    {
        id: 'postman',
        name: 'Postman',
        type: Type.Tool,
        icon: 'https://www.svgrepo.com/show/354202/postman-icon.svg',
        url: 'https://postman.com/',
        mastery: Mastery.Advanced,
    },
    
    {
        id: 'linux',
        name: 'Linux',
        type: Type.Tool,
        icon: 'linux',
        url: 'https://fr.wikipedia.org/wiki/Linux',
        mastery: Mastery.Advanced,
    },
    {
        id: 'windows',
        name: 'Windows',
        type: Type.Tool,
        icon: 'windows8',
        url: 'https://windows.com/',
        mastery: Mastery.Advanced,
    },
    {
        id: 'seo',
        name: 'SEO',
        type: Type.Tool,
        icon: 'https://www.freeiconspng.com/thumbs/seo-icon-png/search-engine-optimization-icon-7.png',
        url: 'https://en.wikipedia.org/wiki/Search_engine_optimization',
        mastery: Mastery.Beginner,
    },
    {
        id: 'express',
        name: 'Express',
        type: Type.Library,
        icon: 'express',
        url: 'https://expressjs.com/',
        mastery: Mastery.Intermediate,
    },
    
    {
        id: 'vite',
        name: 'Vite',
        type: Type.Library,
        icon: 'https://www.svgrepo.com/show/374167/vite.svg',
        url: 'https://vitejs.dev/',
        mastery: Mastery.Intermediate,
    },
    {
        id: 'nextjs',
        name: 'Next.js',
        type: Type.Framework,
        icon: 'nextjs',
        url: 'https://nextjs.org/',
        mastery: Mastery.Advanced,
    },
    {
        id: 'trpc',
        name: 'tRPC',
        type: Type.Library,
        icon: 'https://trpc.io/img/logo.svg',
        url: 'https://trpc.io/',
        mastery: Mastery.Advanced,
    },
    {
        id: 'axios',
        name: 'Axios',
        type: Type.Library,
        icon: 'https://icon.icepanel.io/Technology/svg/Azios.svg',
        url: 'https://axios-http.com/',
        mastery: Mastery.Advanced,
    },
    {
        id: 'strapi',
        name: 'Strapi',
        type: Type.Tool,
        icon: 'https://static-00.iconduck.com/assets.00/strapi-icon-512x505-3hl7a1v3.png',
        url: 'https://strapi.io/',
        mastery: Mastery.Advanced,
    },
    {
        id: 'figma',
        name: 'Figma',
        type: Type.Tool,
        icon: 'figma',
        url: 'https://figma.com/',
        mastery: Mastery.Beginner,
    },
    {
        id: 'storybook',
        name: 'Storybook',
        type: Type.Tool,
        icon: 'storybook',
        url: 'https://storybook.js.org/',
        mastery: Mastery.Intermediate,
    },
    {
        id: 'azure',
        name: 'Azure',
        type: Type.Devops,
        icon: 'azure',
        url: 'https://azure.microsoft.com/',
        mastery: Mastery.Intermediate,
    },
    // {
    //     id: 'terraform',
    //     name: 'Terraform',
    //     type: Type.Devops,
    //     icon: 'terraform',
    //     url: 'https://terraform.io/',
    //     mastery: Mastery.Beginner,
    // },
    {
        id: 'chakra-ui',
        name: 'Chakra UI',
        type: Type.Library,
        icon: 'https://www.coffeeclass.io/logos/chakra-ui.png',
        url: 'https://chakra-ui.com/',
        mastery: Mastery.Advanced,
    },
    {
        id: 'prisma',
        name: 'Prisma',
        type: Type.Library,
        icon: 'https://plugins.jetbrains.com/files/14282/146547/icon/pluginIcon.png',
        url: 'https://prisma.io/',
        mastery: Mastery.Intermediate,
    },
    // {
    //     id: 'vitest',
    //     name: 'Vitest',
    //     type: Type.Library,
    //     icon: 'https://seeklogo.com/images/V/vitest-logo-9ADDA575A5-seeklogo.com.png',
    //     url: 'https://vitest.netlify.app/',
    //     mastery: Mastery.Intermediate,
    // },
    // {
    //     id: 'mikro-orm',
    //     name: 'MikroORM',
    //     type: Type.Library,
    //     icon: 'https://avatars.githubusercontent.com/u/54766168?s=200&v=4',
    //     url: 'https://mikro-orm.io/',
    //     mastery: Mastery.Advanced,
    // },
    // {
    //     id: 'kafka',
    //     name: 'Kafka',
    //     type: Type.Library,
    //     icon: 'https://assets.confluent.io/m/674be3c67bab5343/webimage-icon-kafka-light-SVG',
    //     url: 'https://kafka.apache.org/',
    //     hidden: true
    // },
    {
        id: 'serverless',
        name: 'Serverless',
        type: Type.Library,
        icon: 'https://www.vectorlogo.zone/logos/serverless/serverless-icon.svg',
        url: 'https://serverless.com/',
        mastery: Mastery.Intermediate,
    },
    {
        id: 'hono',
        name: 'Hono',
        type: Type.Framework,
        icon: 'https://private-user-images.githubusercontent.com/44789941/296606255-22f18af0-6893-4596-a425-f89fe9a2448c.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MjA4MDksIm5iZiI6MTcyNjUyMDUwOSwicGF0aCI6Ii80NDc4OTk0MS8yOTY2MDYyNTUtMjJmMThhZjAtNjg5My00NTk2LWE0MjUtZjg5ZmU5YTI0NDhjLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDIxMDE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMGJhZmMyMmRjOTZkYzY0MmEwYWJhMTRkODhmYTllZjc2N2I1OGQwMWE1OWY0MDJlZjU1OTYzNDhjMDMyMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TlBHbg-Z8yEyKZjxlPxndhIl046xji0ZXzerg_v8kuA',
        url: 'https://hono.dev/',
        mastery: Mastery.Intermediate,
    },
    {
        id: 'zod',
        name: 'Zod',
        type: Type.Library,
        icon: 'https://files.svgcdn.io/logos/zod.svg',
        url: 'https://zod.dev/',
        mastery: Mastery.Intermediate,
    },
    {
        id: 'liveblock',
        name: 'Liveblock',
        type: Type.Framework,
        icon: 'https://www.google.com/imgres?q=liveblock%20icon&imgurl=https%3A%2F%2Fwww.finsmes.com%2Fwp-content%2Fuploads%2F2022%2F03%2Fliveblocks.png&imgrefurl=https%3A%2F%2Fwww.finsmes.com%2F2022%2F03%2Fliveblocks-raises-5m-in-seed-funding.html&docid=A1HS7uvRRhZ9eM&tbnid=PkcLJ-SU6eo5HM&vet=12ahUKEwjGtu3P68qIAxUEo68BHaqJBmAQM3oECBwQAA..i&w=400&h=400&hcb=2&ved=2ahUKEwjGtu3P68qIAxUEo68BHaqJBmAQM3oECBwQAA',
        url: 'https://liveblocks.io/',
        mastery: Mastery.Advanced,
    }
]